name: Build Plugin
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        DALAMUD_HOME: /tmp/dalamud

    steps:
      - uses: actions/checkout@v4
        with:
            submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Download Dalamud
        run: |
            wget https://goatcorp.github.io/dalamud-distrib/latest.zip -O ${{ env.DALAMUD_HOME }}.zip
            unzip ${{ env.DALAMUD_HOME }}.zip -d ${{ env.DALAMUD_HOME }}

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release --nologo

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Build
          files: HoardFarm/bin/x64/Release/HoardFarm/**
          make_latest: true

      - name: Show manifest
        run: cat HoardFarm/bin/x64/Release/HoardFarm.json || echo "No manifest found"
