name: Build Plugin
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        DALAMUD_HOME: /tmp/dalamud

    steps:
      - uses: actions/checkout@v4
        with:
            submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Download Dalamud
        run: |
            wget https://goatcorp.github.io/dalamud-distrib/api14/latest.zip -O ${{ env.DALAMUD_HOME }}.zip
            unzip ${{ env.DALAMUD_HOME }}.zip -d ${{ env.DALAMUD_HOME }}

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release --nologo

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: HoardFarm
          path: HoardFarm/bin/x64/Release/HoardFarm/
